# Generated by Django 5.2.3 on 2025-06-20 01:55

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('prefecture', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('address_detail', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[profiles.models.validate_phone_number])),
                ('label', models.CharField(choices=[('home', '自宅'), ('office', '会社'), ('other', 'その他')], default='other', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('prefecture', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('address_detail', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[profiles.models.validate_phone_number])),
                ('label', models.CharField(choices=[('home', '自宅'), ('office', '会社'), ('other', 'その他')], default='home', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
