# Generated by Django 5.2.3 on 2025-06-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='label',
            field=models.CharField(choices=[('home', '自宅'), ('office', '会社'), ('other', 'その他')], default='home', max_length=20),
        ),
    ]
