# Generated by Django 5.2.3 on 2025-06-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_shippingaddress_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee', models.PositiveIntegerField()),
                ('shipping_tax', models.PositiveIntegerField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.PositiveIntegerField()),
                ('billing_last_name', models.CharField(max_length=30)),
                ('billing_first_name', models.CharField(max_length=30)),
                ('billing_postal_code', models.CharField(max_length=7)),
                ('billing_prefecture', models.CharField(max_length=10)),
                ('billing_street_address', models.CharField(max_length=100)),
                ('billing_address_detail', models.CharField(blank=True, max_length=100)),
                ('billing_phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', '未発送'), ('shipped', '発送済')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', '未払い'), ('paid', '支払い済')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'クレジットカード'), ('bank', '現金振込'), ('qr', 'QR決済')], max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
