# Generated by Django 5.2.3 on 2025-06-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightBasedShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
            ],
            options={
                'ordering': ['max_weight'],
            },
        ),
        migrations.DeleteModel(
            name='ShippingFee',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
