# Generated by Django 5.2.3 on 2025-06-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_weightbasedshippingfee_delete_shippingfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='福岡県', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='福岡県', max_length=10),
        ),
    ]
