# Generated by Django 5.2.3 on 2025-06-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('is_milled', models.BooleanField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_discounted', models.BooleanField(default=False)),
                ('organic_method', models.CharField(choices=[('standard', '一般栽培'), ('organic', '有機栽培'), ('reduced_pesticide', '減農薬栽培'), ('special', '特別栽培'), ('pesticide_free', '無農薬栽培')], default='standard', max_length=20)),
            ],
        ),
    ]
